package HelloApp;


/**
* HelloApp/HelloOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Hello.idl
* domingo 13 de marzo de 2022 17H50' CET
*/

public interface HelloOperations 
{
  String sayHello ();
} // interface HelloOperations
